openapi: 3.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Standpoint API
  contact:
    email: you@your-company.com
#tags:
#  - name: admins
#    description: Secured Admin-only calls
#  - name: developers
#    description: Operations available to regular developers
paths:
  /page/main:
    get:
      summary: Надає інформацію про головну сторіеку
      operationId: getPageMain
      parameters:
        - in: query
          name: dateFrom
          schema:
            type: string
        - in: query
          name: dateTo
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventMainPageInfo'

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  schemas:
    EventDates:
      type: object
      properties:
        add_con_start:
          type: string
          format: date
          example: "2025-05-11"
        con_start:
          type: string
          format: date
          example: "2025-05-12"
        client:
          type: string
          format: date
          example: "2025-05-13"
        event_start:
          type: string
          format: date
          example: "2025-05-14"
        event_end:
          type: string
          format: date
          example: "2025-05-15"
        decon_end:
          type: string
          format: date
          example: "2025-05-16"
        add_decon_end:
          type: string
          format: date
          example: "2025-05-18"

    Event:
      type: object
      properties:
        id:
          type: integer
          example: 1
        short_name:
          type: string
          example: "Форум стартапів"
        full_name:
          type: string
          example: "Форум стартапів Довга назва 2025"
        organizer:
          type: object #TODO: Add schema
        event_dates:
          $ref: '#/components/schemas/EventDates'

    EventMainPageInfo:
      type: object
      properties:
        event:
          $ref: '#/components/schemas/Event'
        project_types:
          type: object
          properties:
            pidvis:
              type: object
            standart:
              type: object
              properties:
                counter:
                  $ref: '#/components/schemas/CategoriesCounter'
                
                managers:
                  type: array
                  items:
                    type: object
                    properties:
                      manager:
                        type: object #TODO: Add schema
                      counter:
                        $ref: '#/components/schemas/CategoriesCounter'
                      projects:
                        type: array
                        items:
                          $ref: '#/components/schemas/Project'
            exclusive:
              type: object
    Project:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Абпланалп"
        area:
          type: number
          example: 24.5
        image_ids:
          type: array
          items:
            type: integer
            example: 1
        status:
          type: string
          example: "Первинні переговори"
        manager:
          type: object #TODO: Add schema
        budget:
          type: array
          items:
            $ref: '#/components/schemas/ProjectBudget'
        
    ProjectBudget:
      type: object
      properties:
        id:
          type: integer
          example: 1
        amount:
          type: integer
          example: 12045100
        currency:
          type: string
          example: "грн"
        exchange_rate:
          type: integer
          example: 100
    
    CategoriesCounter:
      type: object
      properties:
        awaiting_contact:
          type: integer
          example: 12
        in_progress:
          type: integer
          example: 8
        finished:
          type: integer
          example: 0
        canceled:
          type: integer
          example: 4
security:
  - bearerAuth: [] # use the same name as above

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/rtfggf/StandPointAPI/1.0.0